FROM debian:bookworm AS platform

RUN apt-get update && apt-get upgrade -y && apt-get install -y cmake

FROM platform AS builders

WORKDIR /tmp/builders
COPY install .
RUN cmake -S . -B build -Wno-dev && cmake --build build --target install_builders

FROM platform AS final

ARG uid=1000
ARG gid=1000

RUN addgroup --system --gid ${gid} builder
RUN adduser --system --uid ${uid} --gid ${gid} builder --home /home/builder

COPY --from=builders /usr/local /usr/local/
COPY --from=builders --chown=${uid}:${gid} /root/go /home/builder/go/

ENV PATH /home/builder/go/bin:/usr/local/bin:/usr/bin

WORKDIR /tmp/mods
RUN chown ${uid}:${gid} .
COPY --chown=${uid}:${gid} mods .

USER ${uid}:${gid}
RUN go mod download
