linters:
  enable:
    - depguard
    - dogsled
    - exportloopref
    - goconst
    - gocritic
    - gofumpt
    - gosec
    - misspell
    - nakedret
    - nolintlint
    - revive
    - stylecheck
    - unconvert
