name: Check Modules
on:
  pull_request:
jobs:
  check-modules:
    name: check modules
    strategy:
      matrix:
        include:
        - name: test
          sonar-token: SONAR_TOKEN_X_TEST
        - name: escrow
          sonar-token: SONAR_TOKEN_X_ESCROW
    uses: ./.github/workflows/module.yml
    with:
      name: ${{ matrix.name }}
    secrets:
      sonar-token: ${{ secrets[matrix.sonar-token] }}
